### ISSUE TITLE
Build action broken, xp toolchain deprecated in vs2022

### ISSUE THREAD

**Issue by Egaliterrier** [ardittristan/cheat-engine#4]
v141_xp seems to no longer be supported/available for vs2022:(

**Comment by ardittristan** [comment]
I'll take a look soon!

**Comment by ardittristan** [comment]
Found the issue, they removed the default installation of the v141 sdk in github runners: [actions/runner-images@`6df3848`](https://github.com/actions/runner-images/commit/6df3848fcdb890c8aaedd2cc6a3ec42088a92d34#diff-d3119a278ce9ce80fc4b5af63a1112fb3a044aec3e6002d838e8eb26d7a3a499L460)

will have to implement caching for that

**Comment by pa-0** [comment]
Hi @ardittristan, thank you for building this adware free version of CE!  Any plans to release 7.6?

**Comment by ardittristan** [comment]
@pa-0 as you can see I'm live with the upstream repo (except for a readme update), so as long as there's no code pushes there there's nothing I can do.

<img width="635" height="88" alt="Image" src="https://github.com/user-attachments/assets/49b2aa7f-11f2-4118-8918-22d86c71170d" />

Also, please make a new issue next time and don't reply to an unrelated issue
